title: My personal blog
author: Mauricio Cardona Jaramillo
url: https://macaja.github.io
baseurl: /
twitter_username: mauriciocj96
github_username:  macaja
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
