title: My personal blog
url: https://macaja.github.io
baseurl: /
twitter_username: mauriciocj96
github_username:  macaja

theme: minima
plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
