title: My personal blog
author: Mauricio Cardona Jaramillo
url: https://macaja.github.io
twitter_username: mauriciocj96
github_username:  macaja
markdown: kramdown
google_analytics: UA-196423121-1
plugins:
  - jekyll-feed
sass:
  style: compact 

